name: E2E tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
    paths-ignore:
    - "*.md"
    - LICENSE
    - "*.yaml"
  pull_request:
    branches:
      - master
    paths-ignore:
    - "*.md"
    - LICENSE
    - "*.yaml"

jobs:
  e2e:
    name: Run e2e tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          lfs: 'true'

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Node.js dependencies
        run: |
          cp chain_params.test.json chain_params.json
          npm ci

      - name: Run e2e tests
        run: npm run cy:ci

